language: python

python:
    - '3.6'
    - '3.7'
    - '3.8'

install: pip install -e ."[dev]"

script: 
    - flake8 gatekeeper/*.py
    - flake8 test/*.py
    - pytest --cov=gatekeeper

deploy:
    provider: pypi
    username: "__token__"
    password:
        secure: cT7srw8YyVJeCjEUD5s2h45B9YQnChjBLzbBZCJRMx1eAd+AYLRJc9sT3d3BTPhlBTEhAkAhfNjsbcZYZQc/Mg3aDJ+Ahb4Xi17F0B4jqtzreU+EpCEAIdmrptoi5bMGJtVMVXmnvxqVNt5shR0v6xNx7eVVkoJew7YPUkZZoITkz4wo2OPx9GL89n96gl9zwV2RLFkVKDuzky42pNTPpnscI1VCZn8dd0HKMpjBpCLi6W877YBRRrgx7R5LfQPNqrZaoCIcXOa3JwbFP2xiHVgPfss2cdM1Ol6/e8wrwcnJX3MqsmMtUcPyWGPg3k6NBDn8MwLpSdDrzfU/5Cl4Mj9Z3pHbwk3ITx9sB1tHg6LmKmj7zPVVsu0EbPa5Uy0wvYwxsMwkEya6C5yWKn/tfwC8Z/sadX0AsXIx+3l0NJSMaPLREqaO89RUVLEdUJH6cOFz5F6N/EAyo8JBKoIe0Cra0DHzc6J/NzxY8iq0frWDyG6ZbK3CflJTWlhTo//fzsyA90QCNS4Kzp0xpqZJX8Sk05nVo4fxJQRuVnRPbLbbWrPNgxkCUCdTtModSsIxlNS2k73RLyuQAD8lFXigc6/VYopjwXzZkJDonCWCoXHyJq1BcT/SkSg19EmlaDJSZdurle/OiVGxnmlhWtBf6q3EsB4el2sQkli+sBOJEMI=
    on:
        tags: true
    skip_existing: true

after_success:
    - coveralls
